[package]
name = "lua_language_server_lad_backend"
description = "LADfile processor for the BMS scripting framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
bevy_mod_scripting_bindings_domain = { workspace = true }
clap = { version = "4", features = ["derive"] }
# mdbook = "0.4"
anyhow = "1"
tera = "1.20"
strum = { version = "0.25", features = ["derive"] }
ladfile = { path = "../../ladfile", version = "0.18.0" }
env_logger = "0.11"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
include_dir = "0.7"
indexmap = "2"
# serde_json = "1.0"
# regex = "1.11"

[dev-dependencies]
assert_cmd = "2.0"
pretty_assertions = "1.4.1"

[lints]
workspace = true

[[bin]]
name = "lad-lls"
path = "src/main.rs"
