[package]
name = "bevy_mod_scripting_rhai"
version = "0.3.0"
authors = ["Maksymilian Mozolewski <makspl17@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Necessary functionality for Rhai support with bevy_mod_scripting"
repository = "https://github.com/makspll/bevy_mod_scripting"
homepage = "https://github.com/makspll/bevy_mod_scripting"
keywords = ["bevy", "gamedev", "scripting", "rhai"]
categories = ["game-development"]
readme = "readme.md"

[package.metadata.release]
pre-release-replacements = [
    {file="Cargo.toml", search='^version\s*=\s*.*$', replace="version = \"{{version}}\"", exactly=1},
    {file="Cargo.toml", search='^(?P<h>bevy_mod_scripting_core\s*=.*)version\s*=\s*".*"(?P<t>.*)$', replace="${h}version = \"{{version}}\"${t}", exactly=1},
]

[lib]
name="bevy_mod_scripting_rhai"
path="src/lib.rs"

[dependencies]
bevy= { version = "0.11", default-features = false}
rhai = { version = "1.15.1", features = ["sync"] }
bevy_mod_scripting_core = {path="../../bevy_mod_scripting_core", version = "0.3.0" }
