[package]
name = "bevy_mod_scripting_rune"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "Necessary functionality for Rune support with bevy_mod_scripting"
repository = "https://github.com/makspll/bevy_mod_scripting"
homepage = "https://github.com/makspll/bevy_mod_scripting"
keywords = ["bevy", "gamedev", "scripting", "rune"]
categories = ["game-development"]
readme = "readme.md"

[lib]
name = "bevy_mod_scripting_rune"
path = "src/lib.rs"

[dependencies]
bevy_mod_scripting_core = { path = "../../bevy_mod_scripting_core", version = "0.4.0" }
bevy = "0.12.1"
rune = "0.13.1"
rune-modules = "0.13.1"
anyhow = "1.0.75"
