[package]
name = "bevy_mod_scripting_rune"
description = "Necessary functionality for Rune support with bevy_mod_scripting"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true


[lib]
name = "bevy_mod_scripting_rune"
path = "src/lib.rs"

[dependencies]
bevy_mod_scripting_core = { workspace = true }
bevy = { workspace = true, default-features = false }
rune = "0.13.1"
rune-modules = "0.13.1"
anyhow = "1.0.75"

[lints]
workspace = true
