[package]
name = "bevy_mod_scripting_rune"
version = "0.9.0-alpha.2"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Necessary functionality for Rune support with bevy_mod_scripting"
repository = "https://github.com/makspll/bevy_mod_scripting"
homepage = "https://github.com/makspll/bevy_mod_scripting"
keywords = ["bevy", "gamedev", "scripting", "rune"]
categories = ["game-development"]
readme = "readme.md"

[lib]
name = "bevy_mod_scripting_rune"
path = "src/lib.rs"

[dependencies]
bevy_mod_scripting_core = { workspace = true }
bevy = { workspace = true, default-features = false }
rune = "0.13.1"
rune-modules = "0.13.1"
anyhow = "1.0.75"

[lints]
workspace = true
