[package]
name = "mdbook_lad_preprocessor"
version = "0.3.1"
description = "Language Agnostic Declaration (LAD) file format for the bevy_mod_scripting crate"
readme = "readme.md"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
env_logger = { workspace = true }
clap = { workspace = true }
ladfile = { workspace = true }
mdbook = { workspace = true, features = ["search"] }
log = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
regex = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "mdbook-lad-preprocessor"
path = "src/main.rs"
