[package]
name = "bevy_mod_scripting_lua"
version = "0.8.0-alpha.3"
authors = ["Maksymilian Mozolewski <makspl17@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Necessary functionality for Lua support with bevy_mod_scripting"
repository = "https://github.com/makspll/bevy_mod_scripting"
homepage = "https://github.com/makspll/bevy_mod_scripting"
keywords = ["bevy", "gamedev", "scripting", "rhai"]
categories = ["game-development"]
readme = "readme.md"

[package.metadata."docs.rs"]
features = ["lua54"]

[package.metadata.release]
enable-features = ["lua54"]

[features]
# enables loading possibly unsafe lua modules by lua scripts
unsafe_lua_modules = []

# enable teal utilities
teal = []

lua51 = ["tealr/mlua_lua51"]
lua52 = ["tealr/mlua_lua52"]
lua53 = ["tealr/mlua_lua53"]
lua54 = ["tealr/mlua_lua54"]
luajit = ["tealr/mlua_luajit"]
luajit52 = ["tealr/mlua_luajit52"]
luau = ["tealr/mlua_luau"]
mlua_serialize = ["tealr/mlua_serialize"]
mlua_macros = ["tealr/mlua_macros"]
mlua_async = ["tealr/mlua_async"]

[lib]
name = "bevy_mod_scripting_lua"
path = "src/lib.rs"

[dependencies]
bevy = { workspace = true, default-features = false }
bevy_mod_scripting_core = { workspace = true }
tealr = { version = "0.9", features = [
    "mlua_vendored",
    "mlua_send",
    "mlua_macros",
] }
parking_lot = "0.12.1"
serde_json = "1.0.81"
anyhow = "1.0.75"
