[package]
name = "bevy_mod_scripting_lua"
version = "0.15.0"
authors = ["Maksymilian Mozolewski <makspl17@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Necessary functionality for Lua support with bevy_mod_scripting"
repository = "https://github.com/makspll/bevy_mod_scripting"
homepage = "https://github.com/makspll/bevy_mod_scripting"
keywords = ["bevy", "gamedev", "scripting", "rhai"]
categories = ["game-development"]
readme = "readme.md"

[package.metadata."docs.rs"]
features = ["lua54"]

[package.metadata.release]
enable-features = ["lua54"]

[features]
# enables loading possibly unsafe lua modules by lua scripts
unsafe_lua_modules = []

lua51 = ["mlua/lua51"]
lua52 = ["mlua/lua52"]
lua53 = ["mlua/lua53"]
lua54 = ["mlua/lua54"]
luajit = ["mlua/luajit"]
luajit52 = ["mlua/luajit52"]
luau = ["mlua/luau"]
mlua_serialize = ["mlua/serialize"]
mlua_macros = ["mlua/macros"]
mlua_async = ["mlua/async"]

[lib]
name = "bevy_mod_scripting_lua"
path = "src/lib.rs"

[dependencies]
bevy = { workspace = true, default-features = false }
bevy_mod_scripting_core = { workspace = true, features = ["mlua_impls"] }
mlua = { version = "0.10", features = ["vendored", "send", "macros"] }
profiling = { workspace = true }

[lints]
workspace = true
