[book]
authors = ["Maksymilian Mozolewski"]
language = "en"
multilingual = false
src = "src"
title = "Bevy Scripting"
description = "Documentation for the Bevy Scripting library"

[output.html]
additional-js = ["multi-code-block.js"]
git-repository-url = "https://github.com/makspll/bevy_mod_scripting"
edit-url-template = "https://github.com/makspll/bevy_mod_scripting/edit/main/docs/{path}"

[preprocessor.lad-preprocessor]
