[book]
authors = ["Maksymilian Mozolewski"]
language = "en"
multilingual = false
src = "src"
title = "Bevy Scripting"
description = "Documentation for the Bevy Scripting library"

[output.html]
additional-js = ["multi-code-block.js", "mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/makspll/bevy_mod_scripting"
edit-url-template = "https://github.com/makspll/bevy_mod_scripting/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1

[preprocessor.lad-preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
