on:
  pull_request:
    paths: 
    - "crates/macro_tests/**"
  push:
    branches:
      - main
    paths: 
      - "crates/macro_tests/**"


name: Run macro tests

jobs:
  tests:
    name: Macro Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clear space
        run: sudo rm -rf /usr/share/dotnet; sudo rm -rf /opt/ghc; sudo rm -rf "/usr/local/share/boost"; sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v3
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd crates/macro_tests && cargo test --profile=ephemereal-build
