on:
  push:
    branches: "fix/bencher"

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Xtask initializer
        run: |
          cargo xtask init
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project bms \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch "fix/bencher" \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --err \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}'
        env:
          BENCHER_CMD: |
            bencher run --adapter rust_criterion "cargo bench --features lua54"